<!-- Generated by documentation.js. Update this documentation by updating the source code. -->

### Table of Contents

-   [Player](#player)
-   [Pong](#pong)

## Player

The player class

## Pong

The pong class

**Parameters**

-   `height` **[number](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Number)** 
-   `width` **[number](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Number)** 
